//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoLaiXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DapAn
    {
        public int MaDapAn { get; set; }
        public int MaCauHoi { get; set; }
        public byte SoThuTu { get; set; }
        public string NoiDung { get; set; }
        public bool DapAnDung { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
    }
}
