//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoTaoLaiXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinChung
    {
        public int Id { get; set; }
        public string GioiThieu { get; set; }
        public string LienHe { get; set; }
    }
}
